[package]
name = "libgit2-config-env-var"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = { git = "https://github.com/clnoll/git2-rs", branch = "libgit2-config-env-var" }